baseURL = "/"
languageCode = "en-us"
title = "Careers - Multidots"
theme = "multidots-careers"

# [permalinks]
#   post = "/post/:slug/"
  
# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Life @ Multidots"
        url     = "/life-at-multidots/"
        weight  = 1
    [[menu.nav]]
        name    = "Recruitment Process"
        url     = "/recruitment-process/"
        weight  = 2
    [[menu.nav]]
        name    = "Current Opening"
        url     = "/careers/"
        weight  = 3
    [[menu.nav]]
        name    = "Submit Resume"
        url     = "/submit-resume/"
        weight  = 4
    [[menu.nav]]
        name    = "About us"
        url     = "/about/"
        weight  = 5


# Parameters passed inside pages

[params]
  logo      = "/images/md-header-logo.png"
  email     = "careers@multidots.com"
  phnnum    = "+91 79 2970 8121"
  facebook  = "https://www.facebook.com/multidots/"
  twitter   = "https://twitter.com/multidots"
  linkedin  = "https://www.linkedin.com/company-beta/312439/"
  instagram = "https://www.instagram.com/multidots/"
  copyright = "© 2018 Multidots Solutions Pvt. Ltd."
  footerdescription = "With a balanced approach to work we understand the diverse needs of individuals on our team. We push you to go beyond your own limits and support you in every responsibility you shoulder, recognizing every dream you have, mentoring you for life rather than only work. Come join us because you make us complete."
  
  # Banner Section
  [params.banner]
      enable    = true
      bannerimg = "images/banner-img.png"
      title     = "What makes us unique is"
      subtitle  = "Relationship"
 
  
  # About us Section
  [params.aboutus]
      enable  = true
      title   = "JOIN OUR TEAM OF INNOVATORS"
      content = "Our quest for engaging outstanding talent inspires us to provide a culture that challenges, inspires and motivates individuals to go beyond their own limits. As a member of our teams you will be a part of the most dynamic group of innovators & thinkers, expert problem-solvers, design geniuses and programming gurus."
    # [params.aboutus.btn]
      btnText    = "Current opening"
      btnURL     = "/careers/"
 
  
  # How We Care Section
  [params.care]
    enable = true
    title  = "How We Care"
 